apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  name: grafana-svc
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: image_grafana:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000