apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc # Este es el nombre para conectar a la base de datos
  labels:
    app: influxdb-app
spec:
  selector:
    app: influxdb-app
  ports:
  - port: 8086
    targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb
        image: image_influxdb:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /var/lib/influxdb
      volumes:
          - name: influxdb-persistent-storage
            persistentVolumeClaim:
              claimName: influxdb-pvc
          
