apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - addresses:
      - 192.168.99.240-192.168.99.240
      name: default
      protocol: layer2