apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  name: nginx-svc 
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    name: http-port
    targetPort: 80
  - port: 443
    name: https-port
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: image_nginx:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443