apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc 
  labels:
    app: telegraf-app
spec:
  selector:
    app: telegraf-app
  ports:
  - port: 8125
    targetPort: 8125
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-app
  template:
    metadata:
      labels:
        app: telegraf-app
    spec:
      containers:
      - name: telegraf
        image: image_telegraf:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 8125

