apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: image_wordpress:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

